 ; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Sierra"
#define MyAppVersion "1.0"
#define MyAppPublisher "Tacitus Kilgore Co."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D2C7C350-D9CC-42B2-A27B-B38DD1B03BA6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={sys}\sc2
DisableDirPage=no
DisableStartupPrompt=yes
DefaultGroupName=None
AllowNoIcons=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=sc
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
;Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Inno Setup 6\Examples\mitmdump.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{code:GetKeyPath}"; DestDir: "{app}"; Flags: external
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
[Code]

var
  KeyFilePage: TInputFileWizardPage;

procedure InitializeWizard();
begin
  KeyFilePage :=
    CreateInputFilePage(
      wpSelectDir,
      'Select Key File Location',
      'Where is your Key file located?',
      'Select where Key file is located, then click Next.');

  KeyFilePage.Add(
    'Location of Key file:',         
    'All files|*.*', 
    '*.*');                             
end;

function GetKeyPath(Param: string): string;
begin
  Result := KeyFilePage.Values[0];
end;


[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Check: "WizardNoIcons"

;[Run]
;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[run]
Filename: {sys}\sc.exe; Parameters: "create mysrv start= auto binPath= ""{app}\mysrv.exe""" ; Flags: runhidden

[UninstallRun]
Filename: {sys}\sc.exe; Parameters: "stop mysrv" ; Flags: runhidden
Filename: {sys}\sc.exe; Parameters: "delete mysrv" ; Flags: runhidden
